Add support for Debian Bookworm
systemli/ansible-role-needrestart pull request #51
Opened 2023-06-16 22:09 UTC by doobry-systemli

I ran the role against Bookworm with molecule to make sure that the config templates are updated and delta between Debian defaults and our templates is minimal.

2023-06-17 08:56 UTC, 0x46616c6b approved these changes

2023-06-17 14:20 UTC, 0x46616c6b requested changes
Can you please also adjust `meta/main.yml` and update the supported versions for that role?

2023-06-18 06:56 UTC, doobry-systemli commented
> Can you please also adjust `meta/main.yml` and update the supported versions for that role?

Good catch, done now.

2023-06-18 07:35 UTC, 0x46616c6b approved these changes

2023-06-18 07:35 UTC, merged